Projekt/JacobRestaurant/JacobRestaurant/Controllers/CategoryController.cs
using JacobRestaurant.Models;
using JacobRestaurant.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace JacobRestaurant.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<ViewResult> List()
        { 
            return View(await _categoryRepository.ListAll());
        }

        public async Task<ViewResult> Details(int id)
        {
            return View(await _categoryRepository.GetById(id));
        }

        public async Task<ViewResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                await _categoryRepository.Add(category);
                return RedirectToAction("List");
            }
            else
                return RedirectToAction("Create");
        }
        public async Task<RedirectToActionResult> Delete(int id)
        {
            await _categoryRepository.Delete(id);
            return RedirectToAction("List");
        }
    }
}

Projekt/JacobRestaurant/JacobRestaurant/Controllers/DishController.cs
using JacobRestaurant.Repositories;
using JacobRestaurant.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace JacobRestaurant.Controllers
{
    public class DishController : Controller
    {
        private readonly IDishRepository _dishRepository;
        private readonly ICategoryRepository _categoryRepository;
        public DishController(IDishRepository dishRepository, ICategoryRepository categoryRepository)
        {
            _dishRepository = dishRepository;
            _categoryRepository = categoryRepository;
        }

        public async Task<ViewResult> List()
        {
            DishListViewModel dishListViewModel = new DishListViewModel();
            dishListViewModel.Dishes = await _dishRepository.ListAll();

            return View(dishListViewModel);
        }

        public async Task<ViewResult> Details(int id)
        {
            return View(await _dishRepository.GetById(id));
        }

        public async Task<ViewResult> Create()
        {
            UpdateDishViewModel updateDishViewModel = new UpdateDishViewModel();
            updateDishViewModel.Categories = await _categoryRepository.ListAll();
            return View(updateDishViewModel);
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Create(UpdateDishViewModel updateDishViewModel)
        {
            if (ModelState.IsValid)
            {
                await _dishRepository.Add(updateDishViewModel.Dish);
                return RedirectToAction("List");
            }
            else
                return RedirectToAction("Create");
            
        }

        public async Task<ViewResult> Update(int id)
        {
            var dish = await _dishRepository.GetById(id);
            UpdateDishViewModel updateDishViewModel = new UpdateDishViewModel();
            updateDishViewModel.Categories = await _categoryRepository.ListAll();
            updateDishViewModel.Dish = dish;
            return View(updateDishViewModel);
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Update(UpdateDishViewModel updateDishViewModel)
        {
            if (ModelState.IsValid)
            {
                await _dishRepository.Update(updateDishViewModel.Dish);
                return RedirectToAction("List");
            }
            else
                return RedirectToAction("Update", updateDishViewModel.Dish.DishId);
        }

        public async Task<RedirectToActionResult> Delete(int id)
        {
            await _dishRepository.Delete(id);
            return RedirectToAction("List");
        }
    }
}

Projekt/JacobRestaurant/JacobRestaurant/Controllers/ReservationController.cs
using JacobRestaurant.Models;
using JacobRestaurant.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace JacobRestaurant.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationRepository _reservationRepository;
        public ReservationController(IReservationRepository reservationRepository)
        {
            _reservationRepository = reservationRepository;
        }

        public async Task<ViewResult> List()
        {
            return View(await _reservationRepository.ListAll());
        }

        public async Task<ViewResult> Details(int id)
        {
            return View(await _reservationRepository.GetById(id));
        }

        public async Task<ViewResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                await _reservationRepository.Add(reservation);
                return RedirectToAction("List");
            }
            else
                return View();
        }
        public async Task<ActionResult> Delete(int id)
        {
            await _reservationRepository.Delete(id);
            return RedirectToAction("List");
        }
    }
}

Projekt/JacobRestaurant/JacobRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JacobRestaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/3eba42aa9f.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JacobRestaurant</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="List">Dishes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="List">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="List">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JacobRestaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>